### ISSUE TITLE
Bug contrôle du joueur en morph

### ISSUE THREAD

**Issue by SirElone** [asanetargoss/metamorph#30]
A chaque fois que je me transforme en un mobs de 1 bloc de haut et moins (comme l'araignée et d'autre mobs de mod )  j'ai le personnage qui avance tous seul et très vite donc cela deviens embêtant pour jouer

**Comment by James103** [comment]
Google Translate output:
Title: "Player control bug in morph"
Description: "Whenever I transform into a mobs of 1 block high and less (like the spider and other mod mobs) I have the character who advances alone and very quickly so it becomes annoying to play"

This basically means that morphs with very small eye height result in imprecision due to the speed/height ratios involved. A possible fix would be to allow slowing down some of the smaller morphs to reduce this speed to height ratio.

**Comment by SirElone** [comment]
Merci pour votre réponse mais j'y connais rien dans les modifications des fichiers. De plus vous n'avezpas répondu complètement, il me manque toujours le problème du fait que le personnage marche tous seul quand je prend l'apparence d'un morph de petite taille.

Je suis incapable de choisir la direction dans où il va, quand je veux contrer le déplacement le personnage s'arrête et quand je lache les touches du clavier il repart dans un course folle

**Comment by asanetargoss** [comment]
If you're using Tropicraft for 1.12, there is an option in the latest version of Tropicraft to disable swim animation in the config, which may fix your problem.

**Comment by SirElone** [comment]
Wouaw vous avez fais vite, et comment vous avez fait pour savoir que j'avais tropicraft ? En 1.12?

Je vais essayer, je vous tiens au courant demain si cela fonctionne.
Merci de votre aide

**Comment by asanetargoss** [comment]
Let's just say you're not the first person to encounter that bug. :)

**Comment by asanetargoss** [comment]
I'm assuming this issue is resolved.
